plugin/AL_USDMayaTestPlugin/AL/UnitTestHarness.cpp, plugin/AL_USDMayaTestPlugin/test_usdmaya.cpp
some small quality-of-life fixes regarding various tests:
- if NO tests are found, then display the ANGRY / red dino, to make it obvious (as this is usually the result of a mistaken test filter - for a period, I thought my tests were all working fine, when it was actually due to a typo in my test name!)
- in test_usdmaya, add a SCOPED_TRACE statement to comparePlugs, so we can pinpoint where something went wrong
=> some small quality-of-life fixes regarding various tests

lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapeCommands.cpp
...or at least set the attribute correctly on the node. The node itself still seems to load the stage (or at least, it ends up displayed in the viewport), so I'm still not sure this is working correctly, but at least the flag does something now!
=> make proxyShapeImport command use the --unloaded flag

lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp, plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ActiveInactive.cpp, plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_TranslatorContext.cpp, translators/MayaReference.cpp, translators/MayaReference.h, translators/tests/testMayaRef.py, translators/tests/testMayaRef.usda, translators/tests/testMayaRefUnloadable.usda
This helps to ensure that work is not lost - it is particulary helpful if you have variants which allow switching between ALMayaReferences and pure-usd representations.
For instance, suppose you have a scene with a lot of robot-ninja-tyrannosaurs fighting, in small groups.  The scene / riggs are heavy, so the animator does not want to have to have them ALL loaded in their scene at once as maya riggs... however, she wants to be able to see them all, so she knows what's visible, etc.
So, to keep his scene managable, any any given time, most of the robo-ninja-trexs are pure-usd / hydra, with say a group of 2 or 3 brought in as full maya-references at any one time.  This change ensures that they can seamlessly switch back-and-forth between the USD and maya-rigg variants, without worrying …
=> Unloads instead of deletes the associated maya reference when the ALMayaReference is (temporarily) removed

lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapeCommands.cpp, lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp, lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.h, lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeSelection.cpp, lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeUI.cpp, plugin/AL_USDMayaTestPlugin/AL/usdmaya/commands/test_ProxyShapeSelect.cpp
Doing this by replacing SdfPathVector(s) with SdfPathHashSets, to ensure uniqueness.
Should also be more efficient, as we do many membership queries (which are much faster with a hash set for large selections).
=> Fixing a crash when a prim is selected multiple times via the command.

plugin/AL_USDMayaTestPlugin/AL/UnitTestHarness.cpp
Useful when debugging tests or writing new ones, as it allows inspection / copying / etc of .ma and .usda files
=> add flag to test harness to keep temp files

lib/AL_USDMaya/AL/usdmaya/cmds/ProxyShapeCommands.h
fixes a potential crash due to deletion of nullptr
=> ProxyShapeSelect: avoid deletion of uninitialized m_helper ptr

lib/AL_USDMaya/AL/usdmaya/module.cpp, lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp, lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.h, lib/AL_USDMaya/AL/usdmaya/nodes/wrapProxyShape.cpp, lib/AL_USDMaya/CMakeLists.txt
adds a python wrapper for a ProxyShape, which currently just has these methods:
- getByName (to construct an instance - you can't use the Class constructor)
- getUsdStage (more accurate than trying to use StageCache, particularly if you have two or more proxy shapes pointing at same USD file)
- resync
- boundingBox
- isRequiredPath
- findRequiredPath
- makeUsdTransformChain
- makeUsdTransforms
- removeUsdTransformChain
- removeUsdTransforms
- destroyTransformReferences
=> adds a python wrapper for a ProxyShape

translators/MayaReference.cpp, translators/tests/testMayaRef.py, translators/tests/testMayaRefLoading.usda
This small PR fixes an issue where maya references were getting reloaded when they shouldn't be because the path check was not accounting for the reference copy number. If a file was referenced more than once and a change notification came in, all the copies would reload even if their path hadn't changed.
I've added a test that demonstrates the issue.
=> fix for ref path check in MayaReference translator

CMakeLists.txt, cmake/modules/FindUSD.cmake
Pretty simplistic FindUSD.cmake, but allows for slightly more standard cmake interface.  Can find USD using either ${USD_ROOT} or ${USD_CONFIG_FILE}, as either cmake var or env var.
=> add a FindUSD.cmake file

lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
Namespace "pxr::" was hardcoded in one spot, which broke our build when we switched to using our own private USD namesapce
- use PXR_NS instead of "pxr" in ProxyShape.cpp
=> allow for custom pxr namespace

translators/MayaReference.cpp
Instead of indiscriminately trying to update a namespace for a maya reference (which errors if the ref is unloaded), only update it if the prim is active and the reference is loaded.
[MayaReference translator] don't try to update a namespace on an unloaded reference
=> MayaReference: avoid error when updating a namespace on an unloaded reference

lib/AL_USDMaya/AL/usdmaya/fileio/translators/TranslatorContext.cpp
When updatePrimTypes was removing prims from the m_primMapping (should
it even do that?), it wasn't using std::vector::erase correctly. As a result, it was trying to dereference invalid iterators, causing occasional crashes.
It should be noted that this only occurs if for some reason your m_primMapping has entries for prims that do not exist in the stage. When removed via a variant switch (or other tracked mechanism), the m_primMapping will be correctly updated before the updatePrimTypes call.
> These entries will be used to update the changelog.
> Use Markdown list syntax for each entry.
> Filled out fields will be added to the changelog.
[TranslatorContext] minor bug where removing previously tracked prims might cause the internal PrimLookup to become out of sync (and possibly crash).
=> fix TranslatorContext::updatePrimTypes crash when removing non-existent prims

CMakeLists.txt, cmake/modules/FindMaya.cmake, lib/AL_USDMaya/CMakeLists.txt, usdutils/AL/usd/utils/CMakeLists.txt
Minimal changes to fix some windows build issue. 
- Adding boost chrono lib only for Windows builds
- Adding Python libraries dependency to fix link error on compile
- Changing the cmake lookup file for plugins as glext.h will not be in a future devkit.
- Linux build failing when looking for boost chrono lib. It is not part of the USD distributable.
- glext.h file lookup on upcoming Maya 2019 devkit failing. File is not part of the devkit anymore.
- Link error while compiling the usdutil module (Missing python27.lib). Adding Python_libraries
=> Adsk contrib/windows build fixes

lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp, lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
Mostly a code organization change, though it does prevent `m_params.showGuides` from being updated twice in `ProxyDrawOverride::prepareForDraw` (once by `ProxyShape::getRenderAttris`, and once in the function body).
Was motivated by some internal tweaks of mine, that needed to call `getRenderAttris`, but organizationally it makes sense that if we're updating showGuides, we should update showRender too.
- make getRenderAttris update showRender, as well as showGuides
=> make getRenderAttris update showRender

lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp, lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.h
Right now, if you switch the renderer (using the RendererManager node) to a progressive renderer like embree, the viewport will only show the "initial" pass, even though computation of the "converged" pass continues in the background.  The only way I've found to update the viewport is by selecting / unselecting the proxy shape.
This change makes the viewport continue to refresh, to show the refined results, until the render is converged.
- Viewport will continue to refresh to show updated progressive renderers (like embree) until converged
=> update the viewport for progressive renderers (like embree)

lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeUI.cpp
Just cleans up some debug prints (that otherwise get crammed on the same line)
- Add missing newlines to some TF_DEBUG statements in ProxyShapeUI
=> ProxyShapeUI: add trailing newline to TF_DEBUG statements

lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
Make sure loadStage is called when a proxyShape is duplicated, so that the new shape is ready for use.
When you duplicate a proxy shape, you wont see anything in the viewport and it wont be fully initialize until you reopen maya or find a hack (like changing the usd path) to trigger a load stage.
=> fix for duplicating proxyShapes

lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
Support layer identifiers for paths that are not on disk until they are resolved. This allows us to use our uri resolver to load layers with `sql:///` identifiers.
To support this, I removed a TfIsFile check and fixed the handling of relative paths if the joined path doesn't exist. We can simply rely on Usd to resolve the identifier and make sure it exists.
support for files that are not on disk until they are resolved
=> Support layer identifiers for paths that are not on disk

lib/AL_USDMaya/AL/usdmaya/nodes/translatorProxyShape.cpp, lib/AL_USDMaya/AL/usdmaya/nodes/translatorProxyShape.h, lib/AL_USDMaya/CMakeLists.txt, lib/AL_USDMaya/plugInfo.json, lib/AL_USDMaya/usdTranslator.cpp, plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_TranslatorProxyShape.cpp, plugin/AL_USDMayaTestPlugin/CMakeLists.txt
Registers a PrimWriter translator for the AL proxyShape in pixar's maya exporter.
This PR can be a jumping off point to discuss future layout workflows with AL_UsdMaya. It also enables AL_usdMaya to be used as an alternative to Pxr assemblies. 
The translator allows an artist to build up a set from proxyShapes loading in smaller usd files.  Each proxyShape becomes a prim with an SdfReference on the exported stage and the proxyShape's session layer is "grafted" onto the exported stage under that prim. Using a reference keeps exports light and including the specs of the session layer allows for a high amount of customization.
While the proxyShape is great for interacting with a single stage, this workflow (like the assembly workflow) makes it easy for artists to use maya nodes to manipulate …
=> add proxyShape translator for layout workflow

lib/AL_USDMaya/AL/usdmaya/CodeTimings.cpp, lib/AL_USDMaya/AL/usdmaya/CodeTimings.h, lib/AL_USDMaya/AL/usdmaya/nodes/RendererManager.cpp, lib/AL_USDMaya/AL/usdmaya/nodes/TransformationMatrix.cpp, usdutils/AL/usd/utils/DiffCore.cpp, utils/AL/event/EventHandler.h
this fixes up a number of compiler warnings (mostly signed/unsigned comparison,
and unused functions), so that AL_USDMaya may be used with PXR_STRICT_BUILD_MODE.
Among other things, this will enable error on issues like functions which should
have a return value, but don't.  Also, even with PXR_STRICT_BUILD_MODE, it will
make warnings stand out more.
- A number of compiler warnings fixed, so PXR_STRICT_BUILD_MODE may be used
=> support PXR_STRICT_BUILD_MODE

lib/AL_USDMaya/AL/usdmaya/Global.cpp
As mentioned in this [issue](https://github.com/AnimalLogic/AL_USDMaya/issues/30),
Currently, the AL_USDMaya plugin clears the selection during the save. This deviates from the expected Maya behaviour and breaks publishers—such as Shotgun Toolkit—which have selection based publishes, where:
1. The user selects the DAG oject in the Outliner they want to publish, hit "publish"
2. The maya scene is saved and published
3. The selected object is exported and published, and flagged as an output product of the published maya scene
To solve this issuse, we store the selection list in preFileSave(), still clear the selection list, but restore the selection in postFileSave(). AL_USD proxies will also be ignored in the storing of the selection, as they will never be part of selection based publishes …
=> Store selection in preFileSave(), and restore it in postFileSave() 

docs/layers.md, lib/AL_USDMaya/AL/usdmaya/fileio/NodeFactory.cpp, lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp, lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.h, lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeSelection.cpp, plugin/AL_USDMayaTestPlugin/AL/usdmaya/commands/test_LayerManagerCommands.cpp, plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_LayerManager.cpp, usdmayautils/AL/usdmaya/utils/Utils.cpp, usdmayautils/AL/usdmaya/utils/Utils.h
Sets the default edit target to the session layer and sanctifies the layer as a place for "session edits" made by maya user's interactions with the stage. 
We believe this default makes a lot of sense and is in line with Usd's philosophy. Some benefits are that:
- Edits won't get mixed into the root layer. A clean session layer can show you exactly what has changed in the scene from the default version of the asset.
- Avoids serializing the root layer in the scene (doing so can be much more data then needed and also sabotages your ability to maintain a live reference to the root layer)
- Highest priority opinion. Avoids any artist confusion if they are making edits that are disregarded because the session layer has an override.
- Useful to concentrate edits in one place so they can be …
=> Sanctify the proxyShape's session layer

lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.cpp, lib/AL_USDMaya/AL/usdmaya/nodes/ProxyDrawOverride.h, lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp, lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.h
Implements VP2 selection in maya2019 thanks to the new MPxDrawOverride::userSelect() interface 
(Duplicated of pull request #108. Now merging into develop branch. Discard pull request #108)  
- Implementation of new ProxyDrawOverride::userSelect() provided with maya2019
- Implementation of ProxyShape::getShapeSelectionMask()
=> support viewport selection in maya2019 VP2 (retry)

cmake/modules/FindMaya.cmake
Fix to resolve #126 where the FindMaya module might fail to find Maya.
The code change is copying the FindMaya module in Pixar's USD repo (https://github.com/PixarAnimationStudios/USD/blob/dev/cmake/modules/FindMaya.cmake) 
- FindMaya cmake module checking MAYA_DEVKIT_INC_DIR before using it
=> Fix FindMaya module not always finding Maya

lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShape.cpp
Adds a Maya refresh command call after objects change (variant switch) in order to trigger a viewport redraw
Refresh command call added at the end of ProxyShape::onObjectsChanged
=> fix variant switch refresh bug
